### ISSUE TITLE
Warning about verify_certs=False despite using the default True

### ISSUE THREAD

**Issue by wsw70** [legrego/homeassistant-elasticsearch#108]
**Environment**
Home-Assistant version: 0.114.3
Elasticsearch version: 7.9.0

Relevant `configuration.yml` settings:
```yml
elastic:
  url: https://elasticsearch.my.domain
```

**Describe the bug**

Upon startup, the following entry is logged once:

```
/usr/local/lib/python3.8/site-packages/elasticsearch_async/connection.py:60: UserWarning: Connecting to elasticsearch.my.domain using SSL with verify_certs=False is insecure.
  warnings.warn(
```

The connection to Elasticsearch is done via HTTPS, with a Let's Encrypt certificate. It seems that  `verify_certs=False` is assumed despite `True` being the default (which should be the case in my configuration).

The connection is correct, events are logged in Elasticsearch.

**Comment by legrego** [comment]
Thanks for the report @wsw70. It seems like the `elasticsearch_async` package that we're using is causing more problems than it solves (see https://github.com/legrego/homeassistant-elasticsearch/issues/107), so I might have to finally drop support for 6.x and migrate to the new elasticsearch python client, which has async built-in.
