### ISSUE TITLE
Are all states logged as a batch?

### ISSUE THREAD

**Issue by wsw70** [legrego/homeassistant-elasticsearch#109]
I have just started to use `homeassistant-elasticsearch` and I see lots of events being logged in ES.

When drilling down, it seems that all of the states are being dumped as it every 30 (?) seconds. 
Is that the case? If so - is there a reason not to log as the state changes (which would yield significantly fewer events)

**Comment by legrego** [comment]
Hey @wsw70,

Yes by default, this component will batch all state changes and publish them every 60 seconds to Elasticsearch. This is configurable by adjusting the `publish_frequency` ([see config options](https://github.com/legrego/homeassistant-elasticsearch#advanced-configuration)).

> is there a reason not to log as the state changes (which would yield significantly fewer events)

The intent was to reduce the number of round trips this component has to make to your Elasticsearch instance. Batching them every X seconds (where X is configurable) is a reasonable tradeoff IMO.

One important note, is that this component will publish the state of all entities on this interval, even if the entity hasn't undergone a state change. This is done to facilitate aggregations for in Kibana for time-series based visualizations. If you don't need this behavior, and only want to publish actual state changes, then you can set `only_publish_changed` to `true`:

```yml
# configuration.yml

elastic:
  # frequency is measured in seconds
  publish_frequency: 60
  only_publish_changed: true
```

**Comment by legrego** [comment]
@wsw70 Does this answer your question?

**Comment by wsw70** [comment]
Yes, thank you for the information @legrego
