### ISSUE TITLE
Dockerfile to build Home-Assistant docker image w/ this built-in?

### ISSUE THREAD

**Issue by jordansissel** [legrego/homeassistant-elasticsearch#116]
**Is your feature request related to a problem? Please describe.**

I'm deploying Hass on my raspberry pi using the docker container method. With this method, the typical upgrade scenario is "docker pull ..." to update the hass image. However, it'd be nice if I had a simple docker image with this component, so perhaps my upgrade scenario would become `docker pull ...; docker build -t hass-with-elasticsearch; docker restart hass-with-elasticsearch` or similar.

**Describe the solution you'd like**

If you think this feature makes sense to live in this repo, I'm happy to send a PR with a Dockerfile to do this.

**Comment by legrego** [comment]
Hey @jordansissel!

Thanks for opening this. I'm not currently inclined to add a Dockerfile to the repo. Folks who install this component are likely to have other custom components installed as well, so I don't feel like many would benefit from this configuration. I could be wrong though, so I'm happy to have a discussion about this, and/or leave this open to see if there is broader interest.

Have you looked into the [HACS component](https://hacs.xyz/)? We publish the latest version to the HACS store, and you can use HACS to manage all of your third-party HASS components.

**Comment by jordansissel** [comment]
Oh I don’t think I’ve heard of HACS. I’ll check it out. Thanks! I’m good to
close this (on email so I can’t)
