### ISSUE TITLE
Remove support for custom Certificate Authorities (`ssl_ca_path`)

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#121]
In order to reduce the complexity of migrating to config flows (https://github.com/legrego/homeassistant-elasticsearch/issues/74), I would like to remove the `ssl_ca_path` option.

The ability to specify a custom CAs is not consistent with the rest of the home-assistant component suite, at least based on my research. We will keep the existing options to enable/disable SSL, and to enable/disable SSL verification.

**Comment by jakommo** [comment]
I'd appreciate if we could keep the option to specify a CA somehow. I'm running my own CA at home and it's also used to secure my Elasticsearch cluster. 

IMO it's a bug that many components do not support this in 2020 and not something we should follow. 
There are also some that do support this [mqtt for example](https://www.home-assistant.io/docs/mqtt/certificate/).

I don't have a strong opinion to add this to the integration UI, but there should be some way to add a CA. 
Especially with HassOS or the supervised docker version, there is no easy way to bake in the CA on an "OS" level.

**Comment by legrego** [comment]
Thanks @jakommo, I appreciate your feedback. I opened this issue to see what kind of reaction I'd get, so it's good to know that this is still being used.

I'll do my best to maintain this setting, and I'll update this issue with any findings as I work through the Config Flow implementation.

Home assistant is really pushing integrations away from yml based config, and I expect that a (far away) future version may very well forbid it.

**Comment by legrego** [comment]
I think I've found a flow that works which won't inconvenience users. I'll post an update here once I have something testable. @jakommo would you be available to test this out once it's ready?

**Comment by jakommo** [comment]
Awesome @legrego . Yes, sure. Let me know when you have something I can test.

**Comment by legrego** [comment]
@jakommo The [latest beta](https://github.com/legrego/homeassistant-elasticsearch/releases/tag/v0.4.0-beta4) maintains support through the new config UI. Would you be able to give this a test when you get some free time?

**Comment by jakommo** [comment]
Just tested it and it works fine after specificity the path to the CA cert in the UI. :heart:

**Comment by legrego** [comment]
Fantastic, thanks for verifying @jakommo. I'll close this one out
