### ISSUE TITLE
Unable to had elastic integration

### ISSUE THREAD

**Issue by YomoShitsu** [legrego/homeassistant-elasticsearch#135]
Hello, 
I followed procedure to had elastic integration. 
The component is available in folder custom_compenents but I can't see it in home assistant GUI when I try to had it through Integrations...

Could you help me please ? 

Home Assistant OS in v2021.2.0 under docker

Thank you so much

**Comment by legrego** [comment]
Hi @YomoShitsu - which version of the component are you running?

The latest beta (`0.4.0-beta2`) is the only version that can be configured in the GUI. Older versions don't have GUI support just yet.

If you're running the latest beta, then can you post a screenshot of your `custom_components` directory, and also a screenshot of your `custom_components/elasticsearch` directory?

Did you restart Home Assistant after installing the integration?

**Comment by YomoShitsu** [comment]
Hello @legrego 
Thank you for your reply. 
Yes I had installed latest beta 0.4.0-beta2 

![image](https://user-images.githubusercontent.com/58432074/107127666-eaa64080-68b7-11eb-805f-f38e2179370a.png)
![image](https://user-images.githubusercontent.com/58432074/107127685-19241b80-68b8-11eb-9cff-7040f93c16dc.png)

Thank you

**Comment by legrego** [comment]
Thanks for the quick response @YomoShitsu -

It looks like the component ended up in the wrong location. It should be in a folder named `elasticsearch`, rather than `elastic/search`.

Can you move the contents of `elastic/search` into an `elasticsearch` folder, and then restart Home Assistant?

**Comment by YomoShitsu** [comment]
Hi @legrego 

You right ! 
I remove folder elastic from custom_components, erase it from hacs, restart Ha, reinstall it and restart ha one more time and I will able ton install it through integration. 
I thought there was an old installation of a stable version ! 
Thanks for your help ! 

Regards

**Comment by legrego** [comment]
Awesome, glad that worked!
