### ISSUE TITLE
How to enable debug logging?

### ISSUE THREAD

**Issue by cavokz** [legrego/homeassistant-elasticsearch#143]
I'm configuring this integration (v0.4.0) for the first time and I've an existing secure self managed ES 7.12.0 instance running on some other machine. I also have configured the hass_writer role and a user with such role.

In following the UI configuration instructions I get an "Insufficient privileges for specified user" error and a 403 status in the hass logs.

I'd like to investigate (ie read the raw API request and response) to/from the ES instance and, in general, get debugging logs. How can I do that?

**Comment by legrego** [comment]
Hey @cavokz, sorry to hear you're having trouble. You can enable this component's debug logging by setting the following in your `configuration.yaml`:

```yml
logger:
  default: info
  logs:
    custom_components.elasticsearch: debug
```

This won't include everything sent/received over the wire, but will hopefully give you enough context to triage further

**Comment by legrego** [comment]
@cavokz Any luck debugging your component setup? Anything I can help with?

**Comment by cavokz** [comment]
@legrego Did not have the opportunity yet.
