### ISSUE TITLE
Allow disabling ILM from the UI configuration flow

### ISSUE THREAD

**Issue by cavokz** [legrego/homeassistant-elasticsearch#144]
I would prefer to configure indices and ILM on my own and therefore give to the hass user only the strictly minimum privileges for creating new documents.

I see that the .yaml configuration would allow this setup but it's marked as deprecated and doesn't look as the way forward for me.

**Comment by legrego** [comment]
This should be possible via the UI configuration flow already:

![image](https://user-images.githubusercontent.com/3493255/118178908-948af100-b402-11eb-8067-c129789711f7.png)

**Comment by cavokz** [comment]
Is it already available in v0.4.0?

**Comment by legrego** [comment]
Yes, this is part of the options flow (The "Configure" button that appears on the integrations's card after initial setup). It's controlled via the `CONF_ILM_ENABLED` property:

https://github.com/legrego/homeassistant-elasticsearch/blob/39b3cf4bd9ebfd599be34e0314128a8f40f1c3f5/custom_components/elasticsearch/config_flow.py#L357-L378

**Comment by cavokz** [comment]
That's why I cannot find it, I cannot pass the initial setup.
