### ISSUE TITLE
Document the development flow

### ISSUE THREAD

**Issue by cavokz** [legrego/homeassistant-elasticsearch#145]
I'd like to get my hands dirty but also avoid reinventing the wheel. What's the best way to setup an efficient development iteration? Could you please document it? Thanks!

**Comment by legrego** [comment]
Thanks for your interest! Yeah I need better docs for sure for this. If you're using Visual Studio Code, then this project includes a [dev container](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) that to my knowledge has only been tested on my machine 🙂.

Opening the project in a dev container will give you a local home-assistant instance with the plugin installed. There is a facility to launch a local Elasticsearch instance within the container as well -- when I get some more time I'll come back here with better instructions for you!

----

If the devcontainer route isn't your cup of tea, then you also have the option of installing this plugin to a local home-assistant instance, and editing the python files in-place. Just remember to restart home-assistant to see your changes reflected.

**Comment by cavokz** [comment]
Nice, I'll give it a try. Thanks!
