### ISSUE TITLE
add elastic api key authentication

### ISSUE THREAD

**Issue by erikveg** [legrego/homeassistant-elasticsearch#148]
My elastic cloud requires an api key authentication.

Could you add this to the configuration and supply the elastic client with the api_key authentication header.

Thanks

**Comment by legrego** [comment]
Thanks @erikveg I agree this would be useful. From a security perspective I think we should prefer an API Key over traditional username/password

**Comment by legrego** [comment]
@erikveg,

Thinking about this a bit more: would you prefer to create the API Key yourself, and store that within this component (like we do with username/password today), or would you like this component to create one automatically, using the configured username/password?

I'm leaning towards the latter, as that, IMO, provides a superior user experience. This way we can automatically create an API Key with a minimal privilege set, which improves security and reduces the chance of user error.

**Comment by erikveg** [comment]
An automatically created api key is fine by me.

Thanks!

Von: Larry Gregory ***@***.***>
Gesendet: Mittwoch, 27. April 2022 21:06
An: legrego/homeassistant-elasticsearch ***@***.***>
Cc: Vegting Erik ***@***.***>; Mention ***@***.***>
Betreff: Re: [legrego/homeassistant-elasticsearch] add elastic api key authentication (#148)


@erikveg<https://github.com/erikveg>,

Thinking about this a bit more: would you prefer to create the API Key yourself, and store that within this component (like we do with username/password today), or would you like this component to create one automatically, using the configured username/password?

I'm leaning towards the latter, as that, IMO, provides a superior user experience. This way we can automatically create an API Key with a minimal privilege set, which improves security and reduces the chance of user error.
