### ISSUE TITLE
How to connect to Elastic Cloud?

### ISSUE THREAD

**Issue by legovaer** [legrego/homeassistant-elasticsearch#150]
It's not clear from the docs how one can connect to Elastic Cloud. Could you elaborate on this please? 😊

**Comment by legrego** [comment]
Hey @legovaer -- the process for connecting to Elastic Cloud should be largely the same as a self-hosted instance.

To get your Elasticsearch URL, click Elasticsearch's `Copy endpoint` link from your deployment overview screen in the Cloud Console:

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/3493255/139667031-f83cfefc-f3a7-42f3-a65b-0ea26d089404.png">

As for username/password, you can create a user within Kibana for this component to use, and assign them a role with the [appropriate privileges](https://github.com/legrego/homeassistant-elasticsearch#security)

**Comment by legrego** [comment]
Please feel free to reopen if you need more assistance
