### ISSUE TITLE
Filtering bug when including specific entities

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#154]
Hmm, I do seem to have stumbled upon some sort of bug. I have this setup:

![image](https://user-images.githubusercontent.com/1118158/168465992-4d16f849-f604-4a98-a4eb-1f6a99699022.png)

But I still occasionally get all of the entities published:
![image](https://user-images.githubusercontent.com/1118158/168466001-d8363397-a3fc-4ece-8e89-82a01464296c.png)

I can't quite determine exactly what the issue is, but it perhaps feels like it publishes all entities without filtering directly after updating the homeassistant-elasticsearch configuration in the UI?

__Originally posted by @chrgro in https://github.com/legrego/homeassistant-elasticsearch/pull/147#issuecomment-1126893906__

**Comment by chrgro** [comment]
Found the issue, please review the linked PR for a fix. I have tested this locally and it now correctly filters the events with the configuration shown in my previous screenshots.
