### ISSUE TITLE
Unable to find elasticsearch in integrations

### ISSUE THREAD

**Issue by p-rintz** [legrego/homeassistant-elasticsearch#163]
**Environment**
Home-Assistant version: 2022.9.4
Elasticsearch version: Trying to use Humio Cloud

Relevant `configuration.yml` settings:
Not using configuration.yml

**Describe the bug**
I am unable to find the "elasticsearch" integration in Home Assistant.

**To Reproduce**
1. Install via HACS
2. Restart HA
3. Go to Integrations
4. Cant find it

**Expected behavior**

**Screenshots**

**Additional context**
Its similar to issue #135 , however I installed via HACS and the folder is in the correct location and I can also see that HA generally has found the elasticsearch integration via this log line:

`2022-09-18 07:48:26.080 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration elasticsearch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

No other log lines were found in regards to elasticsearch. 

I have tried version 0.4.0 and 0.5.0 of this integration as well, but this hasnt helped.
Not sure if you need any further information.

Thanks for your help.

**Comment by legrego** [comment]
Hey @p-rintz, sorry for the delayed response -- I haven't come across this before. Can you try to enable debug logging for this component, and let see if there is anything else that could give us a hint?

```yml
# configuration.yaml
logger:
  default: info
  logs:
    homeassistant.components.elasticsearch: debug
```

**Comment by legrego** [comment]
Please reopen if you're still having trouble
