### ISSUE TITLE
Entities are added several times with each update

### ISSUE THREAD

**Issue by blarrkan** [legrego/homeassistant-elasticsearch#164]
**Environment**
Home-Assistant version: 2022.11.2
Elasticsearch version: 7.16.3

**Describe the bug**
I setup your plugin to send updates to my elasticsearch each 60 seconds, when I check in elasticsearch I can see that I get updates each 60 seconds. But what I noticed is that each entity gets added several time (see screenshot). That will cause a problem when I should aggregate the data later on.

**Expected behavior**
I should only get ONE document/entry per entity each 60 seconds in elasticsearch.

**Screenshots**
![image](https://user-images.githubusercontent.com/5886119/203555186-a691fc17-518b-4d3a-96cc-6d58b40b7aac.png)
![image](https://user-images.githubusercontent.com/5886119/203555318-a2d33203-cfd3-4276-9e4a-a59c867d218c.png)

**Comment by legrego** [comment]
Closing for now, as we don't _currently_ intend to support this configuration
