### ISSUE TITLE
Removed entities stay in plugin options list, making edits impossible

### ISSUE THREAD

**Issue by chrgro** [legrego/homeassistant-elasticsearch#165]
**Environment**
Home-Assistant version: 2022.11.4
Elasticsearch version: 7.15

Relevant `configuration.yml` settings:
```yml
#None
```

**Describe the bug**
If you manually add an entity for the elasticsearch plugin to the "Entities to upload" (same issue with entities to exclude), then later that entity goes away, the entity will remain in the list of things to upload. However the entity will no longer be in the dropdown list that expands when clicking on Entities to upload. That means it is impossible to remove it from the list. Any attempts to click Submit will then fail with the error. 

**To Reproduce**
Add an entity to "Entities to upload"
Remove entity from Home Assistant, e.g. by renaming it in your configuration.yaml or otherwise
Try modify the Entities to Upload list, e.g. by adding a completely unrelated entity.
Get the error below
No way to get rid of error as the old entity does not exist at all
(Workaround: Forced to add a dummy entity with this name, then remove from list, then remove dummy entity from HA)

![image](https://user-images.githubusercontent.com/1118158/204144490-9a0285b3-ac79-4e36-944b-efc0a29ab3c0.png)

**Expected behavior**
Either for non-existent entities that are included to be visible in the dropdown, or for non-existent entities to be removed automatically.

**Screenshots**
See above.

**Additional context**
Happy to help with a patch if you can point me in the roughly right direction.

**Comment by legrego** [comment]
@chrgro sorry for the late reply. I started looking into this a few weeks back, but couldn't test any theories to suggest a fix yet. This is still on my radar, and I'll report back when I have the time to properly dig into this.
