### ISSUE TITLE
Support for OpenSearch 7.10.0

### ISSUE THREAD

**Issue by schuss** [legrego/homeassistant-elasticsearch#167]
**Is your feature request related to a problem? Please describe.**
Currently the addon cannot use OpenSearch (AWS hosted distro of Elastic Search) because it is at version 7.10.0 (and perhaps other config reasons I haven't discovered yet). 

**Describe the solution you'd like**
An option to use AWS hosted OpenSearch, with different version compatibility to support their different versioning scheme.  In the future it would also be great to assist users with the permissioning setup there (at least with a guide, if not automated). 

**Additional context**
I don't imagine there are significant changes to support OpenSearch, but it would be a great option for those who aren't interested in running their own ES cluster or who are familiar with AWS hosting tools.

**Comment by schuss** [comment]
One of the possible config issues, from my logs:

Logger: custom_components.elasticsearch
Source: custom_components/elasticsearch/config_flow.py:153
Integration: Elasticsearch ([documentation](https://github.com/legrego/homeassistant-elasticsearch), [issues](https://github.com/legrego/homeassistant-elasticsearch/issues))
First occurred: 8:54:55 AM (5 occurrences)
Last logged: 8:55:44 AM

Unknown error connecting with Elasticsearch cluster. cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

**Comment by legrego** [comment]
Hey @schuss, thanks for starting this discussion. At this point in time, I'm not interested in supporting both OpenSearch and Elasticsearch within the same component. While they share a common origin, the two products will continue to diverge over time, and having a single component service both of these products would lead to a "lowest common denominator" scenario where we couldn't benefit from the ongoing improvements made to either platform.

I encourage you and/or others to fork this repository as a starting point for an OpenSearch component, if that's something that interests you.
