### ISSUE TITLE
Component does not close open connections which leads to resource exhaustion 

### ISSUE THREAD

**Issue by ankerstal** [legrego/homeassistant-elasticsearch#168]
**Environment**
Home-Assistant version: 2022.12.9
Elasticsearch version: **8.4.3**

**Describe the bug**
It seems that since October this integration does not properly close tcp connections to elasticsearch after use. This leeds to resource exhaustion both when it comes to memory and open tcp connections,. 

**To Reproduce**
  - Start home assistant with this integration running. I have it configured via UI..

**Screenshots**
![image](https://user-images.githubusercontent.com/23146785/210493857-8163a524-2c7a-4c65-8c22-126389f7927f.png)
![image](https://user-images.githubusercontent.com/23146785/210493974-5f035aaa-c44d-46ef-8366-71716a4ee61f.png)

**Comment by legrego** [comment]
Thanks for the report, @ankerstal. I'll take a look when time permits, but I'm also more than happy to accept a PR if you (or anyone else) gets to this before I do.

**Comment by legrego** [comment]
@ankerstal what are you using to track the number of established connections?
