### ISSUE TITLE
Migrate from legacy templates to component templates

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#177]
Elastic deprecated support for templates in favor of composable index templates. We need to migrate to the new APIs in order to maintain compatibility.

New: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html
Deprecated: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html

**Comment by strawgate** [comment]
Fixed by: https://github.com/legrego/homeassistant-elasticsearch/pull/207
