### ISSUE TITLE
What is it used for?

### ISSUE THREAD

**Issue by cociweb** [legrego/homeassistant-elasticsearch#203]
Hello,
Sorry for the following dumb question, but it can be a good topic starter:
I've found this integration in HACS. I have an offline Elasticsearch (with nextcloud), and HA. I' was really curious how is this integration is useful for me. Unfortunately, after I've spent a couple of minutes to read the [readme.md ](https://github.com/legrego/homeassistant-elasticsearch#features)but I've got no closer. I've found a survey about the possibilities how is it used for, but I didn't got even closer.
What are the real life use-cases of this integration? How can it help to me? What are the additional values?

Thank's in advance.

**Comment by legrego** [comment]
I've had too many problems with my refrigerator and freezers maintaining temperature. I have temperature sensors in each, which report to home assistant, which then gets published to Elasticsearch.

Using Kibana's alerting framework, I setup rules to notify me if temperatures are trending in the wrong direction for too long. I probably could accomplish something similar with home assistant automations, but Elastic's rule engine + aggregations are easier for me to reason about for this particular use case.

**Comment by untergeek** [comment]
I track the humidity and temperature in my daughter's snake enclosure/habitat. As above, Elastic's Alerting framework is nicer for the kind of monitoring I'm doing, so I prefer to use that.

**Comment by untergeek** [comment]
Also, I can keep a smaller subset of data (individual stats I care about) for a very long time compared to the limited amount of retention I can manage with HA and MariaDB/MySQL. This allows _very_ long-term trend analysis for weather data, for example.

**Comment by legrego** [comment]
If someone is willing, I think it'd be great to convert this conversation into a PR to provide inspiration for new users getting started with this component. Either a new section in the README, or a new document that's linked from the README.

Respond here if you're interested. We'll wait a few days to see if there are any other examples from the community.

**Comment by jeanfabrice** [comment]
I'm in!
