### ISSUE TITLE
Using deprecated attribute for ILM

### ISSUE THREAD

**Issue by bdauvissat** [legrego/homeassistant-elasticsearch#216]
**Environment**
Home-Assistant version: 2024.3.1
Elasticsearch version: 8.12.2

**Describe the bug**
On the second screen of the settings, we can choose ILM specifications. The "Max index size" is a deprecated setting and will be removed in future versions.

Instead, the "Maximum primary shard size" setting should be used.

**Comment by strawgate** [comment]
As of https://github.com/legrego/homeassistant-elasticsearch/pull/207 the new default for 8.7+ Elasticsearch will be to use Datastreams which no longer use this deprecated setting.
