### ISSUE TITLE
Add Ingest Pipeline settings

### ISSUE THREAD

**Issue by bdauvissat** [legrego/homeassistant-elasticsearch#217]
**Is your feature request related to a problem? Please describe.**
Adding Ingest Pipelines in the settings. 
Sometimes, some values (in the field "hass.entity.value" as an example) are numeric but in the mapping, they are defined as a keyword. 
Having it in a numeric format can be useful for creating dashboards.

**Describe the solution you'd like**
Adding an "Ingest Pipeline name" in the integration settings can be useful for people wanting to use one.

**Additional context**
Ingest pipeline documentation : https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html

**Comment by bdauvissat** [comment]
That's great news, thanks. 
I stick on the Ingest Pipeline just to offer more capabilites anybody might want to add.

**Comment by strawgate** [comment]
Once https://github.com/legrego/homeassistant-elasticsearch/pull/207 has merged you'll be able to specify a custom ingest pipeline by creating a component template called metrics-homeassistant@custom with content of

```
PUT _component_template/metrics-homeassistant@custom
{
  "template": {
    "settings": {
      "index.default_pipeline": "metrics-homeassistant-pipeline",
    }
  }
}
```

Component template changes apply when the datastream performs a rollover so the first time you modify the template you may need to manually initiate ILM rollover to start applying the pipeline.

**Comment by strawgate** [comment]
Fixed by https://github.com/legrego/homeassistant-elasticsearch/pull/207
