### ISSUE TITLE
Isolate Document Creator

### ISSUE THREAD

**Issue by strawgate** [legrego/homeassistant-elasticsearch#222]
I'd like to consider isolating Document Creator to not have a dependency system_info or the hass_config.

This would simplify testing of the document creator by not requiring us to initialize hass or rely on system_info. We could achieve this by having the publisher initialize the document creator with the list of desired static fields.

Let me know your thoughts

**Comment by legrego** [comment]
I'm not sold on this, yet. Prior to https://github.com/legrego/homeassistant-elasticsearch/pull/197, the creation of documents lived inside of the publisher, but it was getting hard to reason about.

What I like about the current setup is that the publisher does not need to know anything about document structure. It only concerns itself with queueing up HA events, and sending them to ES.
Similarly, the doc creator is the single source of truth for the fields that we populate.

Moving static fields into the publisher will negate both of these benefits.
