### ISSUE TITLE
Fix ConfigEntry migration

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#226]
Our `async_migrate_entry` function needs to be updated. It relies on functionality that was recently deprecated.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:156

> Detected that custom integration 'elasticsearch' sets "data" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/elasticsearch/__init__.py, line 152: config_entry.data = {**new}, please create a bug report at https://github.com/legrego/homeassistant-elasticsearch/issues

> Detected that custom integration 'elasticsearch' sets "version" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/elasticsearch/__init__.py, line 153: config_entry.version = 4, please create a bug report at https://github.com/legrego/homeassistant-elasticsearch/issues

**Comment by strawgate** [comment]
The way we've been migrating config data and options results in a copy of all options existing under data, so i'll clean those up as well

**Comment by strawgate** [comment]
fixed by https://github.com/legrego/homeassistant-elasticsearch/pull/272
