### ISSUE TITLE
Consider using Host Docker for running ES

### ISSUE THREAD

**Issue by strawgate** [legrego/homeassistant-elasticsearch#230]
We should consider mounting the docker daemon into the container (or using DinD) via something like `"mounts": ["source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind"]` and adjusting the run_es script to start a docker container that bootstraps itself. This will allow easy debugging/running multiple versions of ES without having to modify what is installed in the container.

**Comment by legrego** [comment]
Sounds like a good idea to me
