### ISSUE TITLE
Consider supporting Datastreams in 8.0 to 8.6

### ISSUE THREAD

**Issue by strawgate** [legrego/homeassistant-elasticsearch#232]
Right now we only support datastreams starting with 8.7 due to that being the first version that supports TSDS.

We could offer an option to support normal datastreams which would support 8.0 to 8.7 ( I think).

Converting a non TSDS data stream to a TSDS data stream is relatively trivial if the user upgrades.

Im not entirely sold on this as pre-8.7 is EOL but I don't think it would be hard to do and would help ensure that most users start with the "modern" method

**Comment by legrego** [comment]
I'm not entirely sold on this, either. At this point, I don't believe it's worth the additional complexity. I'm happy to leave this issue open for others to chime in with their opinions.

Anecdotally, I've found most folks that choose to run this component keep their clusters relatively up-to-date.
