### ISSUE TITLE
[Chore] Improve configuration management

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#242]
This component was built in an era before Config Entries and Config Flows. As such, the functions and classes that comprise this component make use of raw configuration (`dict`), and do not make a distinction between setup config and options. We should take incremental steps to clean this up:

- [x] Ensure that component _setup_ is stored within config entry `data`
- [x] Ensure that optional component configuration is stored within config entry `options`
- [x] Update our usage of config to read settings from the correct location. Optionally abstract reading values into a class which can provide type-safety.

**Comment by strawgate** [comment]
fixed by https://github.com/legrego/homeassistant-elasticsearch/pull/272
