### ISSUE TITLE
Add support for Floors and Labels

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#249]
A future version of Home Assistant will introduce Floors and Labels to help users further organize their HA asseets (https://rc.home-assistant.io/blog/2024/03/27/release-20244/). I believe these attributes would be useful additions to our event schema.

I don't yet know how Home Assistant plans to include these in their own data model, so it is premature to propose specific field mapping changes at this time. We can re-evaluate once the release is official.

**Comment by strawgate** [comment]
Are we ok with making HA 2024.4.2 and Python 3.12 the minimum version for the project?

They bumped minimum python to 3.12 and so we'd need to update the dev container and poetry dependencies to be able to work on this

**Comment by strawgate** [comment]
Or perhaps we could install HA separately from Poetry so that we can run a different HA version than what's in Poetry?
