### ISSUE TITLE
Entity attribute fields should respect ECS

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#250]
ECS [naming guidelines](https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html#_guidelines_for_field_names) state:

> Guidelines for field names
> - Field names must be lower case
> - Combine words using underscore
> - No special characters except underscore

We do not correctly handle these cases. In my test setup, I see attributes with mixed casing, and words separated by whitespace. I suspect we also do not sanitize non-underscore "special characters", either.

![Larry Gregory 2024-03-28 at 08 53 43](https://github.com/legrego/homeassistant-elasticsearch/assets/3493255/8264eb3e-7bfd-44ba-aebc-ba2212252628)

**Comment by strawgate** [comment]
Happy to make a PR for this. I also have been considering having explicit mappings for certain known attributes so that we don't end up with `.float` for all attributes

**Comment by legrego** [comment]
> Happy to make a PR for this. I also have been considering having explicit mappings for certain known attributes so that we don't end up with `.float` for all attributes

Ah I wish I saw this sooner! I just raised a PR, but I'm happy to entertain a different approach if you wanted to explore explicit mappings for certain known attributes.
