### ISSUE TITLE
Sets are not serialized correctly - documents do not publish to ES

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#26]
If a set of items is present in the `attributes` of an entity's state, then the document will fail to index, because we need to transform it into an array (ES does not have the concept of "sets").

See https://github.com/legrego/homeassistant-elasticsearch/issues/23#issuecomment-417907535

https://github.com/elastic/elasticsearch-py/issues/744#issuecomment-373131251

**Comment by legrego** [comment]
@MrBoggi,

Can you try the version here and let me know if that fixes the error you were seeing:

https://github.com/legrego/homeassistant-elasticsearch/tree/serialize-sets

**Comment by MrBoggi** [comment]
@legrego I have updated here now and restarted HA server. It seems like the errors are gone and also getting more data into Elasticsearch. I will follow up tomorrow and see how it has performed during the night.
