### ISSUE TITLE
Support watcher jobs

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#31]
We should support creating a watcher job to send alerts if HASS data hasn't been sent to Elasticsearch within a specific period of time. This is useful to detect internet outages or local network/HASS issues.

**Comment by sejnub** [comment]
My guess is that most potential users will not purchase a license so it might make more sense to support a free alerting solution (that doesn't need more than the free basic license) like elastalert instead of watcher. That way we could target at a bigger group.
