### ISSUE TITLE
manifest.json version is out of date

### ISSUE THREAD

**Issue by andrewkroh** [legrego/homeassistant-elasticsearch#313]
The version number in the `custom_components/elasticsearch/manifest.json` is not synced with the release version. The version is displayed in Home Assistant. This led me to believe that my upgrade through HACS failed so I repeated the install from source which yielded the same result.

<img width="597" alt="Screenshot 2024-05-17 at 19 05 49" src="https://github.com/legrego/homeassistant-elasticsearch/assets/4565752/e5584d22-7144-4c80-9c7f-ab23adb2c164">

## References

https://github.com/legrego/homeassistant-elasticsearch/blob/f1119043475a384ec30c7949221835fdf71f6475/custom_components/elasticsearch/manifest.json#L16

**Comment by strawgate** [comment]
https://github.com/legrego/homeassistant-elasticsearch/releases/tag/v0.7.2
