### ISSUE TITLE
Support publishing to multiple clusters

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#319]
Currently, our ConfigFlow enforces a single instance. This was done to simplify the original implementation, and was a holdover from the legacy yml-based config.

I would like to have this component support multiple active configurations. I often use this component as a sample dataset when testing new ES deployments, and allowing a single instance to communicate to multiple clusters would be helpful.

**Comment by strawgate** [comment]
I will include this in my 2.0 PR, looks like a very easy change
