### ISSUE TITLE
`hass.object_id` should be a property of the `entity`

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#323]
The location of `hass.object_id` feels out of place. Our mapping should reflect the fact that it is a property of the `entity`.

I propose moving `hass.object_id` to `hass.entity.object_id` as part of the `1.0` or `2.0` release. We can optionally alias this field to release it sooner, but I don't personally have a pressing need for this.

Releasing this as part of `2.0` is easier than doing so in `1.0`, so I've marked this as a `Version 2.0 milestone` for now (https://github.com/legrego/homeassistant-elasticsearch/milestone/2)

**Comment by strawgate** [comment]
Sounds good, I can include this in one of my PRs coming up!

**Comment by strawgate** [comment]
hass.entity.object.id? or object_id?

**Comment by legrego** [comment]
> hass.entity.object.id? or object_id?

I fell way behind on my GH notifications, I'm sorry for not responding. We went with `hass.entity.object.id` for 2.0. Closing as resolved.
