### ISSUE TITLE
Missing component diagnostics

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#332]
Our HASSfest validation step is failing because we have certified as a `gold` or better integration, but we are missing diagnostics.

This is a new requirement that we should satisfy. Documentation on this appears sparse, so we may need to dig into HA's core code to understand how to use this.

From https://developers.home-assistant.io/docs/integration_quality_scale_index:
> When communicating with a device or service, the integration implements the diagnostics platform which redacts sensitive information.

From our GH action:
> Integrations: 1
> Invalid integrations: 1
> 
> Integration elasticsearch - /github/workspace/custom_components/elasticsearch:
> Error: R] [MANIFEST] gold integration does not implement diagnostics

**Comment by strawgate** [comment]
https://github.com/legrego/homeassistant-elasticsearch/pull/333/commits/fe5fa12c8a7470e7fa0905c05c1593f35b6e35d8
