### ISSUE TITLE
remove homeassistant version from requirements.txt? 

### ISSUE THREAD

**Issue by jakommo** [legrego/homeassistant-elasticsearch#39]
Currently the requirements.txt lists `homeassistant==0.69.1`. When I installed this plugin a few weeks ago, the first thing I did was `pip install -r requirements.txt` (without really checking the content) and this resulted in a downgrade of my homeassistant which was already at `0.77` or so.

I think it would make sense to drop `homeassistant` from the `requirements.txt`, as this is an addon to homeassistant and I feel it's safe to assume someone who installs this plugin is already running homeassistant. 
The other solution could be to use something like `>=`  which would not downgrade HA if it's already installed 

Thoughts?

**Comment by legrego** [comment]
That's an interesting thought, I hadn't considered that people would think to run the installer. `requirements.txt` should only be used by TravisCI when running the linters.

That being said, I think it'd make sense to change it to `>=`. This would prevent downgrades in your scenario, and it'd still allow travis to take advantage of this. Alternatively (or additionally), we could rename `requirements.txt` to something like `requirements.travis.txt` to make its usage clearer.
