### ISSUE TITLE
Integration exits with error when xpack security is disabled

### ISSUE THREAD

**Issue by mike12806** [legrego/homeassistant-elasticsearch#399]
**Environment**
Home-Assistant version: 2024.12.2
Elasticsearch version: 8.16.1
Integration version: 2.0.0-RC3

Relevant `configuration.yml` settings:
```yml
# Do not include your Elasticsearch URL, credentials, or any other sensitive information
elastic:
  ...
```

**Describe the bug**

**To Reproduce**
1. Go to integration 
2. Enter elasticsearch url as http://192.168.1.2:9200
4. See “unknown” error in UI

**Expected behavior**

should connect successfully 

**Screenshots**

**Additional context**

Logs:

`logger:%20aiohttp.server%0ASource%3A%20/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451%0AFirst%20occurred:%207:11:57%20PM%20(1%20occurrences)%0ALast%20logged:%207:11:57%20PM%0A%0AError%20handling%20request%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway_8.py%22,%20line%20315,%20in%20_error_converter%0A%20%20%20%20yield%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway_8.py%22,%20line%20209,%20in%20has_privileges%0A%20%20%20%20response%20=%20await%20self.client.security.has_privileges(**privileges)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch8/_async/client/security.py%22,%20line%201811,%20in%20has_privileges%0A%20%20%20%20return%20await%20self.perform_request(%20%20%23%20type:%20ignore%5Breturn-value%5D%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20%20%20...%3C7%20lines%3E...%0A%20%20%20%20)%0A%20%20%20%20%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch8/_async/client/_base.py%22,%20line%20423,%20in%20perform_request%0A%20%20%20%20return%20await%20self._client.perform_request(%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20%20%20...%3C7%20lines%3E...%0A%20%20%20%20)%0A%20%20%20%20%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch8/_async/client/_base.py%22,%20line%20271,%20in%20perform_request%0A%20%20%20%20response%20=%20await%20self._perform_request(%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20%20%20...%3C6%20lines%3E...%0A%20%20%20%20)%0A%20%20%20%20%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch8/_async/client/_base.py%22,%20line%20352,%20in%20_perform_request%0A%20%20%20%20raise%20HTTP_EXCEPTIONS.get(meta.status,%20ApiError)(%0A%20%20%20%20%20%20%20%20message=message,%20meta=meta,%20body=resp_body%0A%20%20%20%20)%0Aelasticsearch8.BadRequestError:%20BadRequestError(400,%20'no%20handler%20found%20for%20uri%20%5B/_security/user/_has_privileges%5D%20and%20method%20%5BPOST%5D',%20'no%20handler%20found%20for%20uri%20%5B/_security/user/_has_privileges%5D%20and%20method%20%5BPOST%5D')%0A%0ADuring%20handling%20of%20the%20above%20exception,%20another%20exception%20occurred:%0A%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py%22,%20line%20480,%20in%20_handle_request%0A%20%20%20%20resp%20=%20await%20request_handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py%22,%20line%20569,%20in%20_handle%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py%22,%20line%20117,%20in%20impl%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/security_filter.py%22,%20line%2092,%20in%20security_filter_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/forwarded.py%22,%20line%20210,%20in%20forwarded_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/request_context.py%22,%20line%2026,%20in%20request_context_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/ban.py%22,%20line%2086,%20in%20ban_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/auth.py%22,%20line%20242,%20in%20auth_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/headers.py%22,%20line%2032,%20in%20headers_middleware%0A%20%20%20%20response%20=%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/helpers/http.py%22,%20line%2073,%20in%20handle%0A%20%20%20%20result%20=%20await%20handler(request,%20**request.match_info)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/decorators.py%22,%20line%2081,%20in%20with_admin%0A%20%20%20%20return%20await%20func(self,%20request,%20*args,%20**kwargs)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/config/config_entries.py%22,%20line%20222,%20in%20post%0A%20%20%20%20return%20await%20super().post(request,%20flow_id)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/data_validator.py%22,%20line%2074,%20in%20wrapper%0A%20%20%20%20return%20await%20method(view,%20request,%20data,%20*args,%20**kwargs)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py%22,%20line%20122,%20in%20post%0A%20%20%20%20result%20=%20await%20self._flow_mgr.async_configure(flow_id,%20data)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/data_entry_flow.py%22,%20line%20367,%20in%20async_configure%0A%20%20%20%20result%20=%20await%20self._async_configure(flow_id,%20user_input)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/data_entry_flow.py%22,%20line%20414,%20in%20_async_configure%0A%20%20%20%20result%20=%20await%20self._async_handle_step(%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20%20%20%20%20%20%20flow,%20cur_step%5B%22step_id%22%5D,%20user_input%0A%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20%20%20)%0A%20%20%20%20%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/data_entry_flow.py%22,%20line%20517,%20in%20_async_handle_step%0A%20%20%20%20result:%20_FlowResultT%20=%20await%20getattr(flow,%20method)(user_input)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/logger.py%22,%20line%2053,%20in%20decorated_func%0A%20%20%20%20return%20await%20call_and_log_enter_exit(func,%20logger,%20logging.INFO,%20*args,%20**kwargs)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/config_flow.py%22,%20line%20116,%20in%20async_step_user%0A%20%20%20%20await%20Elasticsearch8Gateway.async_init_then_stop(**prospective_settings)%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway_8.py%22,%20line%20153,%20in%20async_init_then_stop%0A%20%20%20%20await%20gateway.async_init()%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway_8.py%22,%20line%20119,%20in%20async_init%0A%20%20%20%20await%20super().async_init()%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway.py%22,%20line%2074,%20in%20async_init%0A%20%20%20%20if%20not%20await%20self._has_required_privileges():%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway.py%22,%20line%20214,%20in%20_has_required_privileges%0A%20%20%20%20response%20=%20await%20self.has_privileges(privileges=self.settings.minimum_privileges)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/logger.py%22,%20line%2073,%20in%20decorated_func%0A%20%20%20%20return%20await%20async_call_and_log_enter_exit(func,%20logger,%20logging.DEBUG,%20*args,%20**kwargs)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/logger.py%22,%20line%20114,%20in%20async_call_and_log_enter_exit%0A%20%20%20%20result%20=%20await%20func(*args,%20**kwargs)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway_8.py%22,%20line%20208,%20in%20has_privileges%0A%20%20%20%20with%20self._error_converter(msg=%22Error%20checking%20user%20privileges%22):%0A%20%20%20%20%20%20%20%20%20~~~~~~~~~~~~~~~~~~~~~%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.13/contextlib.py%22,%20line%20162,%20in%20__exit__%0A%20%20%20%20self.gen.throw(value)%0A%20%20%20%20~~~~~~~~~~~~~~%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway_8.py%22,%20line%20394,%20in%20_error_converter%0A%20%20%20%20raise%20CannotConnect(append_root_cause(err,%20msg))%20from%20err%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20~~~~~~~~~~~~~~~~~%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/elasticsearch/es_gateway_8.py%22,%20line%20302,%20in%20append_root_cause%0A%20%20%20%20root_cause%20=%20err.info.get(%22error%22,%20%7B%7D).get(%22root_cause%22,%20%5B%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0AAttributeError:%20'str'%20object%20has%20no%20attribute%20'get'%0A`

**Comment by strawgate** [comment]
Can you share what permissions your user/API key is configured with?

The 2.0 release changes moves to datastreams which changes the required permissions. Did you update the user account or API key to match the new required permissions?

**Comment by mike12806** [comment]
It’s unauthed. I’m already using data streams (pre upgrade).

**Comment by mike12806** [comment]
Sorry - few more details on my setup. 

Elasticsearch is hosted in Kubernetes, but exposed on my LAN via a cluster load balancer. 

I can curl from home assistant in a terminal app to http://192.168.1.2:9200 or (via nginx proxy manager) https://log-ingest.mfaherty.net, and both return:

```
{
  "name" : "elasticsearch-ingest-4",
  "cluster_name" : "elastic",
  "cluster_uuid" : "Bp9rtp8hR2KBvm_LszUdFg",
  "version" : {
    "number" : "8.16.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "ffe992aa682c1968b5df375b5095b3a21f122bf3",
    "build_date" : "2024-11-19T16:00:31.793213192Z",
    "build_snapshot" : false,
    "lucene_version" : "9.12.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

Which is making me think there's no connectivity / networking issue....

**Comment by strawgate** [comment]
Yeah for some reason it looks like it's attempting to verify permissions but there's no user.

We test no auth but we don't test security being disabled completely so let me attempt to reproduce and will follow-up soon.

**Comment by mike12806** [comment]
> Yeah for some reason it looks like it's attempting to verify permissions but there's no user.
> 
> We test no auth but we don't test security being disabled completely so let me attempt to reproduce and will follow-up soon.

Maybe a naiive question but what's the difference between auth and security?

**Comment by strawgate** [comment]
If you disable security in Elasticsearch it disables the user and permissions APIs entirely. 

You can enable security but allow anonymous access or enable security but disable TLS.

We use one of the permissions apis to check if the current connection has the permissions we require. This API is not available if you disable security.

**Comment by strawgate** [comment]
Hey, this issue got closed because the related PR merged for the 2.0.0 branch. I will re-open the issue for now until you can confirm that updating to the latest v2.0.0 resolves your issue.

**Comment by mike12806** [comment]
> Hey, this issue got closed because the related PR merged for the 2.0.0 branch. I will re-open the issue for now until you can confirm that updating to the latest v2.0.0 resolves your issue.

Hi - just confirming this is now working for me with v2.0.0 RC4 without security.
