### ISSUE TITLE
Add include_domains and include_entities

### ISSUE THREAD

**Issue by ooii** [legrego/homeassistant-elasticsearch#49]
**Is your feature request related to a problem? Please describe.**
Currently, the configuration file allows for excluding domains and entities. If one needs to send only few data to ES, then she/he needs to add all other domains to the `exclude_domains` array.

**Describe the solution you'd like**
Add `include_domains` and `include_entities` with a precedence that included entities override excluded domains (and that excluded entities override include domains?).

**Comment by legrego** [comment]
Thanks for the suggestion! I'll see what it takes to add this, unless you (or someone else) wants to give it a shot.

**Comment by joostvanmourik** [comment]
Can you also send me the the version with include, i only wan't to use this for my Toon data (5 entities)

**Comment by jakommo** [comment]
Hey @joostvanmourik , this functionality hasn't been added yet, you can follow the PR https://github.com/legrego/homeassistant-elasticsearch/pull/50 for the conversation on this topic. 
If you are used to python, you could also try merging in the changes manually on your local machine from this diff https://github.com/legrego/homeassistant-elasticsearch/pull/50/files, but judging from the conversation in the PR it's not done yet and hasn't been tested, so it might be worth to wait for it to be merged.

**Comment by joostvanmourik** [comment]
> Hey @joostvanmourik , this functionality hasn't been added yet, you can follow the PR #50 for the conversation on this topic.
> If you are used to python, you could also try merging in the changes manually on your local machine from this diff https://github.com/legrego/homeassistant-elasticsearch/pull/50/files, but judging from the conversation in the PR it's not done yet and hasn't been tested, so it might be worth to wait for it to be merged.

Thanx i'am not very good with Pyton so for now i just try to exclude as much as possible :-)

**Comment by legrego** [comment]
I have a PR up to add support for this: https://github.com/legrego/homeassistant-elasticsearch/pull/147
I still need to test this before merging, but the changes were fairly minimal
