### ISSUE TITLE
The folder structure has to be changed to comply with hass v 0.88.0

### ISSUE THREAD

**Issue by sejnub** [legrego/homeassistant-elasticsearch#51]
**Environment**
Home-Assistant version: 0.88.0
Elasticsearch version: 6.6

**Describe the bug**
With version 0.88.0 hass.io throws the following two errors:

- Error loading custom_components.elastic.sensor. Make sure all dependencies are installed
- Integrations need to be in their own folder. Change sensor/elastic.py to elastic/sensor.py. This will stop working soon.

The plugin still seems to work but fine. But according to this article <https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html> the folder structure has to be changed.

**Comment by legrego** [comment]
Thanks for the report @sejnub! I had missed this announcement
