### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by markwalkom** [legrego/homeassistant-elasticsearch#67]
**Describe the solution you'd like**
This is relatively new, but [HACS](https://custom-components.github.io/hacs/) is a replacement for `custom_updater` and it'd be great to be able to keep this extension in sync using it :)

**Additional context**
See link above, but also https://custom-components.github.io/hacs/developer/general/

**Comment by legrego** [comment]
Thanks for the request @markwalkom, I hadn't seen HACS before. If I'm understanding [the requirements](https://custom-components.github.io/hacs/developer/integration/) correctly, I think we can support this just by resolving https://github.com/legrego/homeassistant-elasticsearch/issues/62.

I'll work on #62 first, and then see if it satisfies the requirements for HACS.

**Comment by markwalkom** [comment]
Thanks heaps for the quick turn around on this one, I can see it already showing up :D

![Screen Shot 2019-07-08 at 10 28 57](https://user-images.githubusercontent.com/3184718/60775919-39837580-a16b-11e9-8d72-7b370c6e7751.png)
![Screen Shot 2019-07-08 at 10 29 03](https://user-images.githubusercontent.com/3184718/60775920-3b4d3900-a16b-11e9-908f-486290732129.png)
