### ISSUE TITLE
exclude attribute change

### ISSUE THREAD

**Issue by kkellner** [legrego/homeassistant-elasticsearch#78]
I have an outlet that contains an attribute "current_power_w".  The value of this attribute changes constantly which is causing a log entry in Elastic.   Is there a way to ignore the change of this attribute without excluding the entire outlet on/off state change?

**Comment by legrego** [comment]
We can't exclude attribute changes yet, but you can exclude the entire outlet by using the `exclude.entities` configuration option. Assuming the outlet is called `switch.my_outlet`:


```yml
elastic:
  exclude:
    entities: ['switch.my_outlet']
``` 

See other example configurations here: https://github.com/legrego/homeassistant-elasticsearch#example-configurations

**Comment by kkellner** [comment]
Ok, that is what I thought.  Thanks for your help.

**Comment by legrego** [comment]
Rather than excluding specific attributes, what do you think about a setting where we only publish an entry to Elasticsearch if the entity's `value` has changed? This would essentially exclude all attribute changes. To make things simpler, I think I'd apply this to the entire integration, as opposed to a per-entity basis.

**Comment by legrego** [comment]
I think the best way to solve this is to change the `only_publish_changed` boolean flag to a `publish_mode` option instead. Something like:

publish_mode:
 - `all`: publish all entities regardless of state change
 - `any_changed`: publish only those entities which have had either a `value` or `attribute` changed
 - `value_changed: publish only those entities which have had their `value` changed
