### ISSUE TITLE
Enable only health monitoring

### ISSUE THREAD

**Issue by JohanAke1** [legrego/homeassistant-elasticsearch#80]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like a possibility to only enable health monitoring of the Elasticsearch stack. So a way to disable publishing events would be really nice.

**Comment by legrego** [comment]
Thanks for opening this! I like the idea, and shouldn’t be too difficult to implement. Out of curiosity, what version of Elasticsearch are you running?

**Comment by JohanAke1** [comment]
Im using the newest docker image from Elastic, which is 7.5.1.
