### ISSUE TITLE
Show firing of Automations from Home Assistant

### ISSUE THREAD

**Issue by JZ-SmartThings** [legrego/homeassistant-elasticsearch#93]
**Is your feature request related to a problem? Please describe.**
There is no problem and this is certainly an enhancement. Currently you can only see state values and it works wonderfully. However, if there's ability to subscribe to automation firing events, that would be pretty amazing. I've been using my Kibana for a long time and absolutely love it but now joining Grafana to the force. Below is a query that Grafana shows to me as a list from my MariaDB used by Home Assistant:
```
select last_updated as 'time', json_value(attributes,'$.friendly_name') as 'metric'
from states
where entity_id like 'automation.%'
order by last_updated
```

**Describe the solution you'd like**
Would love to see automation firing events with all applicable attributes not just the current state every X seconds.

**Additional context**

Thanks for considering!

**Comment by JZ-SmartThings** [comment]
This is likely functional as desired if Issue 94 gets resolved: https://github.com/legrego/homeassistant-elasticsearch/issues/94

**Comment by legrego** [comment]
Thanks for the report - I can confirm that #91 / #94 will resolve this, so I will close this for now. Feel free to reopen if for some reason the fix doesn't meet your needs!
